In [1]:
%matplotlib notebook
import numpy as np
import crystaltools.crystal_generator as cg
import crystaltools.crystal_visualizer as cv
import matplotlib.pyplot as plt
import matplotlib as mpl
from mpl_toolkits.mplot3d import proj3d

In [4]:
unit = cg.get_unit_cell('fcc primitive', 2.8)

v1 = np.array([-1., 1., 0.])
v2 = np.array([1., 1., 1.])

v3 = np.cross(v1, v2)

v1 = np.array([1., 0., 0.])
v2 = np.array([0., 1., 0.])
v3 = np.cross(v1, v2)


sc = unit.create_supercell(10, 10, 10, name='supercell')
# sc = unit.create_supercell(4,4,4, name='supercell')
newcell = unit.create_new_orientation(v1, v2, v3, name='new orientation')
newcell.reorient()

# Rmat = create_rotation_matrix(v1, v2)
# newcell.rotate_crystal(Rmat)

dist = sc.find_distance_peroidic()

a0 = sc.scale
ep = a0 * 1.e-5
d0 = 0.
d1 = a0*(1./np.sqrt(2.))
d2 = a0

idn1 = sc.get_neighbor_list(dmax=d1+ep, dmin=d0+ep)
idn2 = sc.get_neighbor_list(dmax=d2+ep, dmin=d1+ep)

rcar = sc.rcar


Getting neighbor distances (periodic): 100%



In [6]:
idn1[:5]

[array([  1,   9,  10,  19,  90,  91, 100, 109, 190, 900, 901, 910]),
 array([  0,   2,  10,  11,  91,  92, 100, 101, 191, 901, 902, 911]),
 array([  1,   3,  11,  12,  92,  93, 101, 102, 192, 902, 903, 912]),
 array([  2,   4,  12,  13,  93,  94, 102, 103, 193, 903, 904, 913]),
 array([  3,   5,  13,  14,  94,  95, 103, 104, 194, 904, 905, 914])]

In [7]:
sc.rcar

array([[-14. , -14. , -14. ],
       [-12.6, -12.6, -14. ],
       [-11.2, -11.2, -14. ],
       ..., 
       [  8.4,   8.4,  11.2],
       [  9.8,   9.8,  11.2],
       [ 11.2,  11.2,  11.2]])

In [8]:
sc.rrel

array([[-0.5, -0.5, -0.5],
       [-0.4, -0.5, -0.5],
       [-0.3, -0.5, -0.5],
       ..., 
       [ 0.2,  0.4,  0.4],
       [ 0.3,  0.4,  0.4],
       [ 0.4,  0.4,  0.4]])

In [9]:
sc.lattvec

array([[ 5.,  5.,  0.],
       [ 5.,  0.,  5.],
       [ 0.,  5.,  5.]])